apiVersion: v1
kind: ConfigMap
metadata:
  name: www-index
  namespace: develop
  labels:
    app: www-index
    env: dev
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>www index</title>
    </head>
    <body>
        <h1>www index 2022</h1>
    </body>
    </html>